In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
df = pd.read_csv("yelp_dataset_csv/yelp_academic_dataset_review.csv")
df.head()

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15

In [36]:
df_business = pd.read_csv("yelp_dataset_csv/yelp_academic_dataset_business.csv")

In [37]:
df_business_philadelphia = df_business[(df_business["state"] == "PA") &
                                       (df_business["categories"].str.contains("Restaurants"))]
#clean the business ids
df_business_philadelphia_rest["business_id"] = (
    df_business_philadelphia_rest["business_id"]
    .str.replace(r"^\-+", "", regex=True)
)
df['business_id'] = (df['business_id'].str.replace(r"^\-+", "", regex=True))

df_business_philadelphia_review = pd.merge(df_business_philadelphia_rest, df, on="business_id")

In [38]:
df_business_philadelphia_rest.count()

business_id     52268
name            52268
address         51825
city            52268
state           52268
postal_code     52247
latitude        52268
longitude       52268
stars           52268
review_count    52268
is_open         52268
attributes      51703
categories      52268
hours           44990
dtype: int64

In [39]:
df_business_philadelphia_review.groupby("business_id").size().reset_index(name="count")

                  business_id  count
0      0-3NcAbA1zeChqWeH454Ng     15
1      0-7N3z_cb3Z1xMGDrbez6w    405
2      0-9PkkpEM53bTgUQo-ls9g    197
3      0-BLZd37lMUODMuYAtKgkA     63
4      0-CQlqMMOrwMhy4EgW4tfw     61
...                       ...    ...
52263  zzjFdJwXuxBOGe9JeY_EMw     48
52264  zznJox6-nmXlGYNWgTDwQQ     30
52265  zznZqH9CiAznbkV6fXyHWA     12
52266  zzu6_r3DxBJuXcjnOYVdTw      8
52267  zzyx5x0Z7xXWWvWnZFuxlQ      8

[52268 rows x 2 columns]

In [40]:
#validate

review_counts_actual = (
    df_business_philadelphia_review
    .groupby("business_id")
    .size()
    .reset_index(name="actual_review_count")
)

df_validate_review_count = pd.merge(
    df_business_philadelphia_rest[["business_id", "review_count"]],
    review_counts_actual,
    on="business_id",
    how="left"
)

df_validate_review_count["valid"] = (
    df_validate_review_count["review_count"] == df_validate_review_count["actual_review_count"]
)

In [41]:
df_invalid = df_validate_review_count[df_validate_review_count["valid"] == False]
df_invalid

                  business_id  review_count  actual_review_count  valid
0      MTSW4McQd7CbVtyjqoe9mw            80                   87  False
4      eEOYSgkmpB90uNA7lDOMRA            10                   11  False
5      il_Ro8jwPlHresjw9EGmBg            28                   29  False
6      0bPLkL0QhhPO5kt1_EXmNQ           100                  106  False
7      MUTTqe8uqyMdBl186RmNeA           245                  250  False
...                       ...           ...                  ...    ...
52257  gPr1io7ks0Eo3FDsnDTYfg            21                   22  False
52258  wVxXRFf10zTTAs11nr4xeA            55                   59  False
52261  2MAQeAqmD8enCT2ZYqUgIQ           204                  213  False
52262  w_4xUt-1AyY2ZwKtnjW0Xg           998                 1034  False
52264  cM6V90ExQD6KMSU3rRB5ZA            33                   34  False

[32018 rows x 4 columns]

In [42]:
df_validate_review_count["difference"] = (
    df_validate_review_count["review_count"] -
    df_validate_review_count["actual_review_count"]
)

df_validate_review_count["difference"].describe()

count    52268.000000
mean        -3.122216
std          6.135465
min       -128.000000
25%         -3.000000
50%         -1.000000
75%          0.000000
max          1.000000
Name: difference, dtype: float64

In [43]:
df_validate_review_false = df_validate_review_count[df_validate_review_count["valid"] == False]
df_validate_review_false

,business_id,review_count,actual_review_count,valid,difference
0,MTSW4McQd7CbVtyjqoe9mw,80,87,False,-7
4,eEOYSgkmpB90uNA7lDOMRA,10,11,False,-1
5,il_Ro8jwPlHresjw9EGmBg,28,29,False,-1
6,0bPLkL0QhhPO5kt1_EXmNQ,100,106,False,-6
7,MUTTqe8uqyMdBl186RmNeA,245,250,False,-5
...,...,...,...,...,...
52257,gPr1io7ks0Eo3FDsnDTYfg,21,22,False,-1
52258,wVxXRFf10zTTAs11nr4xeA,55,59,False,-4
52261,2MAQeAqmD8enCT2ZYqUgIQ,204,213,False,-9
52262,w_4xUt-1AyY2ZwKtnjW0Xg,998,1034,False,-36
52264,cM6V90ExQD6KMSU3rRB5ZA,33,34,False,-1